sonar.projectKey=CoohCooh_TI-WebControl
sonar.organization=coohcooh
sonar.projectName=TI-WebControl
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/dist/**, template/config.template.xml